// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARMBgu4G9tunek3XrAPMW90QkA5yv5DwE',
    appId: '1:1018458639740:web:5dc2899244e23d0b5d28f9',
    messagingSenderId: '1018458639740',
    projectId: 'e-book-app-389116',
    authDomain: 'e-book-app-389116.firebaseapp.com',
    storageBucket: 'e-book-app-389116.appspot.com',
    measurementId: 'G-49BHV10Y88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1d4_Lx-FoR4dwvcc0IGMqPW1F20Ik1qw',
    appId: '1:1018458639740:android:8b6337de6aa957745d28f9',
    messagingSenderId: '1018458639740',
    projectId: 'e-book-app-389116',
    storageBucket: 'e-book-app-389116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqSPecNXGWANp2QE8YF33QCysPXYTReTE',
    appId: '1:1018458639740:ios:1948fbc283b782115d28f9',
    messagingSenderId: '1018458639740',
    projectId: 'e-book-app-389116',
    storageBucket: 'e-book-app-389116.appspot.com',
    androidClientId: '1018458639740-jtvc3h32bjodshnd9c2187ommd59r79r.apps.googleusercontent.com',
    iosClientId: '1018458639740-fvhgo7gctei1oof87ta59fj8o9ko1cdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqSPecNXGWANp2QE8YF33QCysPXYTReTE',
    appId: '1:1018458639740:ios:1948fbc283b782115d28f9',
    messagingSenderId: '1018458639740',
    projectId: 'e-book-app-389116',
    storageBucket: 'e-book-app-389116.appspot.com',
    androidClientId: '1018458639740-jtvc3h32bjodshnd9c2187ommd59r79r.apps.googleusercontent.com',
    iosClientId: '1018458639740-fvhgo7gctei1oof87ta59fj8o9ko1cdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );
}
